import * as express from "express";
import VerifyPermissions from "../../Middleware/VerifyPermissions.js";
import AddLogs from "../../Functions/AddLogs.js";
import { getAllRedirects, getSpecificRedirect, addRedirect, deleteRedirect } from "../../Controllers/Redirect/RedirectController.js";
const router = new express.Router();
router.post('/add',  VerifyPermissions('admin'), AddLogs('Add Redirect', 'green'), addRedirect);
router.get('/all',  VerifyPermissions('admin'), getAllRedirects);
router.get('/get/:slug', getSpecificRedirect);
router.delete('/delete/:id',  VerifyPermissions('admin'), AddLogs('Delete Redirect', 'red'), deleteRedirect);
export default router;
