import * as express from "express";
import Auth from "../../Middleware/Auth.js";
import CreateRole from "../../Controllers/Role/CreateRoleController.js";
import UpdateRole from "../../Controllers/Role/UpdateRoleController.js";
import DeleteRole from "../../Controllers/Role/DeleteRoleController.js";
import GetSingleRole from "../../Controllers/Role/GetRoleController.js";
import GetAllRole from "../../Controllers/Role/GetAllRoleController.js";
import VerifyPermission from "../../Middleware/VerifyPermissions.js";
import AddLogs from "../../Functions/AddLogs.js";
const router = express.Router();
router.post("/create", Auth, VerifyPermission("canManageRole"), AddLogs("Create Role", "green"), CreateRole);
router.post("/update/:id", Auth, VerifyPermission("canManageRole"), AddLogs("Update Role ", "blue"), UpdateRole);
router.delete("/remove/:id", Auth, VerifyPermission("canManageRole"), AddLogs("Delete role", "red"), DeleteRole);
router.get("/get/all", Auth, VerifyPermission("canManageRole"), GetAllRole);
router.get("/get/:id", Auth, GetSingleRole);
export default router;
