import * as express from "express";
import CreateRole from "../../Controllers/Role/CreateRoleController.js";
import UpdateRole from "../../Controllers/Role/UpdateRoleController.js";
import DeleteRole from "../../Controllers/Role/DeleteRoleController.js";
import GetSingleRole from "../../Controllers/Role/GetRoleController.js";
import GetAllRole from "../../Controllers/Role/GetAllRoleController.js";
import VerifyPermission from "../../Middleware/VerifyPermissions.js";
import AddLogs from "../../Functions/AddLogs.js";
const router = express.Router();
router.post("/create",  VerifyPermission("admin"), AddLogs("Create Role", "green"), CreateRole);
router.post("/update/:id",  VerifyPermission("admin"), AddLogs("Update Role ", "blue"), UpdateRole);
router.delete("/remove/:id",  VerifyPermission("admin"), AddLogs("Delete role", "red"), DeleteRole);
router.get("/get/all",  VerifyPermission("admin"), GetAllRole);
router.get("/get/:id",  GetSingleRole);
export default router;
