import * as express from "express";
import LoginRoute from "./LoginRoute.js";
import RegisterRoute from "./RegisterRoute.js";
import Auth from "../../Middleware/Auth.js";
import VerifyPermissions from "../../Middleware/VerifyPermissions.js";
import * as GetAllUserController from "../../Controllers/Auth/GetAllUserController.js";
import * as DeleteUserController from "../../Controllers/Auth/DeleteUserController.js";
import * as UpdateUserController from "../../Controllers/Auth/UpdateUserController.js";
import * as GetUserById from "../../Controllers/Auth/GetUserById.js";
import AddLogs from "../../Functions/AddLogs.js";
const router = express.Router();
router.use("/login", LoginRoute);
router.use("/register", RegisterRoute);
router.get("/get/all", Auth, VerifyPermissions("canManageUser"), GetAllUserController.GetAllUser);
router.delete("/delete/:id", Auth, VerifyPermissions("canManageUser"), AddLogs("Delete user", "red"), DeleteUserController.Delete);
router.post('/update/:id', Auth, VerifyPermissions("canManageUser"), AddLogs("Update user", "Blue"), UpdateUserController.Update);
router.get("/get/:id", Auth, VerifyPermissions("canManageUser"), GetUserById.GetUserById);
export default router;
