import * as express from "express";
import Auth from "../../Middleware/Auth.js";
import VerifyPermissions from "../../Middleware/VerifyPermissions.js";
import * as ThemesController from "../../Controllers/Themes/ThemeController.js";
import AddLogs from "../../Functions/AddLogs.js";
const router = express.Router();
router.get("/", Auth, VerifyPermissions("canManagePlugins"), ThemesController.getThemeInstalled);
router.get("/installable", Auth, VerifyPermissions("canManagePlugins"), ThemesController.getInstallableThemes);
router.post("/install/:id", Auth, VerifyPermissions("canManagePlugins"), AddLogs("Install a new theme", "green"), (req, res) => ThemesController.InstallTheme(req, res, router));
router.get("/all", Auth, VerifyPermissions("canManagePlugins"), ThemesController.getAllThemes);
router.post("/update/:id", Auth, VerifyPermissions("canManagePlugins"), AddLogs("Update plugin", "info"), (req, res) => ThemesController.UpdateTheme(req, res, router));
router.get("/current", ThemesController.getCurrentTheme);
router.get("/default", ThemesController.getDefaultTheme);
export default router;
