import * as express from "express";
import Auth from "../../Middleware/Auth.js";
import VerifyPermissions from "../../Middleware/VerifyPermissions.js";
import * as PluginsController from "../../Controllers/Plugins/PluginsController.js";
import AddLogs from "../../Functions/AddLogs.js";
import { loadAllPlugins } from "../../Functions/LoadPlugin.js";
const router = express.Router();
router.get("/", Auth, VerifyPermissions("canManagePlugins"), PluginsController.getPluginsInstalled);
router.get("/installable", Auth, VerifyPermissions("canManagePlugins"), PluginsController.getInstallablePlugins);
router.post("/install/:id", Auth, VerifyPermissions("canManagePlugins"), AddLogs("Install a new plugin", "green"), (req, res) => PluginsController.InstallPlugin(req, res, router));
router.get("/all", Auth, VerifyPermissions("canManagePlugins"), PluginsController.getAllPlugins);
router.post("/update/:id", Auth, VerifyPermissions("canManagePlugins"), AddLogs("Update plugin", "info"), (req, res) => PluginsController.UpdatePlugin(req, res, router));
router.get("/user-routes", PluginsController.getUserRoutes);
loadAllPlugins(router);
export default router;
