import * as express from "express";
import Auth from "../../Middleware/Auth.js";
import VerifyPermissions from "../../Middleware/VerifyPermissions.js";
import GetPage from "../../Controllers/Pages/GetPageController.js";
import UpdatePage from "../../Controllers/Pages/UpdatePageController.js";
import DeletePage from "../../Controllers/Pages/DeletePageController.js";
import CreatePage from "../../Controllers/Pages/CreatePageController.js";
import AddLogs from "../../Functions/AddLogs.js";
import { GetAllPage } from "../../Controllers/Pages/GetAllPageController.js";
const router = express.Router();
router.get('/get/all', GetAllPage);
router.get("/get/:slug", GetPage);
router.delete("/delete/:id", Auth, VerifyPermissions("canManagePages"), AddLogs("Delete Page", "red"), DeletePage);
router.post("/update/:id", Auth, VerifyPermissions("canManagePages"), AddLogs("Update page", "green"), UpdatePage);
router.post("/create", Auth, VerifyPermissions("canManagePages"), AddLogs("Create page", "green"), CreatePage);
export default router;
