import * as express from "express";
import VerifyPermissions from "../../Middleware/VerifyPermissions.js";
import Auth from "../../Middleware/Auth.js";
import DeleteLogs from "../../Controllers/LogController/DeleteLogsController.js";
import GetLogs from "../../Controllers/LogController/GetLogsController.js";
import Addlogs from "../../Functions/AddLogs.js";
const router = express.Router();
router.delete("/delete", Auth, VerifyPermissions("canDeleteLogs"), Addlogs("Delete Logs", "red"), DeleteLogs);
router.get("/get", Auth, VerifyPermissions("canGetLogs"), GetLogs);
export default router;
