import * as express from "express";
import VerifiyPermissions from "../../Middleware/VerifyPermissions.js";
import { getAllArticles } from "../../Controllers/Article/ArticleController.js";
import { createArticle } from "../../Controllers/Article/ArticleController.js";
import { modifyArticle } from "../../Controllers/Article/ArticleController.js";
import { deleteArticle } from "../../Controllers/Article/ArticleController.js";
import { saveDraft} from "../../Controllers/Article/ArticleController.js";
import { getArticleBySlug } from "../../Controllers/Article/ArticleController.js";
const router = express.Router();
router.get('/all', { getAllArticles }.getAllArticles);
router.post('/create', VerifiyPermissions("admin"), { createArticle }.createArticle);
router.put('/update/:slug',VerifiyPermissions("admin"), { modifyArticle }.modifyArticle);
router.delete('/delete/:slug', VerifiyPermissions("admin"), { deleteArticle }.deleteArticle);
router.post('/draft/', VerifiyPermissions("admin"), { saveDraft }.saveDraft);
router.get('/:slug', { getArticleBySlug }.getArticleBySlug);
export default router;
