import * as express from "express";
import Auth from "../../Middleware/Auth.js";
import VerifiyPermissions from "../../Middleware/VerifyPermissions.js";
import { getAllArticles } from "../../Controllers/Article/ArticleController.js";
import { createArticle } from "../../Controllers/Article/ArticleController.js";
import { modifyArticle } from "../../Controllers/Article/ArticleController.js";
import { deleteArticle } from "../../Controllers/Article/ArticleController.js";
import { saveArticle } from "../../Controllers/Article/ArticleController.js";
import { getArticleBySlug } from "../../Controllers/Article/ArticleController.js";
const router = express.Router();
router.get('/all', { getAllArticles }.getAllArticles);
router.post('/create', Auth, VerifiyPermissions("canManageArticle"), { createArticle }.createArticle);
router.put('/update/:slug', Auth, VerifiyPermissions("canManageArticle"), { modifyArticle }.modifyArticle);
router.delete('/delete/:slug', Auth, VerifiyPermissions("canManageArticle"), { deleteArticle }.deleteArticle);
router.post('/save/:id', Auth, VerifiyPermissions("canManageArticle"), { saveArticle }.saveArticle);
router.get('/:slug', { getArticleBySlug }.getArticleBySlug);
export default router;
